services:
  app-dev:
    profiles: ["dev"]
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/app
    environment:
      - DEAD_DROP_ADDRESS=0.0.0.0
      - DEAD_DROP_DB_HOST=db
      - DEAD_DROP_DB_PORT=8080
    depends_on:
      - db

  app-init:
    profiles: ["prod"]
    container_name: app-init
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - init
    restart: no
    environment:
      - DEAD_DROP_DB_HOST=db
      - DEAD_DROP_DB_PORT=8080
    depends_on:
      - db

  app:
    profiles: ["prod"]
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - serve
    ports:
      - 3000:3000
    restart: always
    environment:
      - DEAD_DROP_ADDRESS=0.0.0.0
      - DEAD_DROP_DB_HOST=db
      - DEAD_DROP_DB_PORT=8080
    depends_on:
      - app-init

  db:
    profiles: ["dev", "prod"]
    container_name: db
    image: ghcr.io/tursodatabase/libsql-server:v0.24.17
    ports:
      - 8080:8080
    restart: always
    volumes:
      - data:/var/lib/sqld

volumes:
  data:
    driver: local
